global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] # Сам Prometheus

  - job_name: 'pvz-service' # Ваше Go приложение
    static_configs:
      # Используйте имя сервиса из docker-compose и порт метрик (9000)
      - targets: ['pvz-app:9000']

  - job_name: 'node-exporter'
    static_configs:
      # Используйте имя сервиса из docker-compose
      - targets: ['node-exporter:9100']

  - job_name: 'postgres-exporter'
    static_configs:
      # Используйте имя сервиса из docker-compose
      - targets: ['postgres-exporter:9187']