global:
  scrape_interval: 15s # Как часто собирать метрики

scrape_configs:
  - job_name: 'pvz-service'
    # Метрики будут собираться с адреса pvz-app:9000 (имя сервиса из docker-compose)
    static_configs:
      - targets: ['pvz-app:9000']